#!/bin/bash

if ! [ -z ${1} ]; then
  if [ -f ${1} ]; then
    version=$(cat ${1})
    tmp_ifs="${IFS}"
    IFS="-"
    version=(${version})
    version_date=${version[0]}
    version_build=${version[1]}
    IFS="${tmp_ifs}"
    if [ "$(date +%Y%m%d)" == "${version_date}" ]; then
      version_build=$((${version_build} + 1))
    else
    	version_date=$(date +%Y%m%d)
    	version_build=1
    fi
    echo "${version_date}-${version_build}" > ${1}
  else
    echo "$(date +%Y%m%d)-1" > ${1}
  fi
else
  echo "Usage: $(basename $0) <VERSION_FILE>"
fi
