#!/bin/bash

if ! [[ -z ${1} && -z ${2} ]]; then
  version_date=$(date +%G%j%H%M)
  version_build=1
  echo "${version_date}" > ${1}
  echo "${version_build}" > ${2}
  echo "Version is now ${version_date}-${version_build}"
else
  echo "Usage: $(basename $0) <VERSION_FILE> <VERSION_BUILD>"
fi
