#!/bin/bash -e

if [ -f /boot/boot.cmd ]; then
  echo "Configuring boot.cmd to use kernel version ${1}."
  sed -i 's/^setenv kernel_version.*/setenv kernel_version '"${1}/" /boot/boot.cmd
  mkimage -C none -A arm -T script -d "/boot/boot.cmd" "/boot/boot.scr"  > /dev/null 2>&1
else
  echo "WARNING: /boot/boot.cmd not found. Bootloader was not update"
fi
