.TH ARMSTRAP-NAND-INSTALLER "8" "April 2015" "Transfert SD card to NAND partition"
.SH NAME
armstrap-sunxi-tools \- Tools to transfert the content of the SD card to the NAND partition of sunxi devices.
.SH SYNOPSIS
.B armstrap-nand-installer <cubieboard|cubieboard2|cubietruck>
.SH AUTHOR
Written by Eddy Beaupre
.SH "REPORTING BUGS"
Report bugs relative to armStrap at https://github.com/armStrapTools/armStrap/
.SH COPYRIGHT
Copyright \(co 2015 Eddy Beaupre
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
