#! /bin/sh
### BEGIN INIT INFO
# Provides:          gensshkeys
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Regenerate SSH keys at first boot
# Description:       This script is called to regenerate
#                    ssh keys, it will uninstall itself automatically.
### END INIT INFO

# Author: Eddy Beaupre <eddy@beaupre.biz>

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
NAME=gensshkeys
SCRIPTNAME=/etc/init.d/$NAME


# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Generating new SSH keys" "$NAME"
	/bin/rm /etc/ssh/ssh_host_*
	/usr/sbin/dpkg-reconfigure openssh-server
	/usr/sbin/update-rc.d -f $NAME remove
	;;
  stop|status|reload|restart|force-reload)
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|status|reload|restart|force-reload}" >&2
	exit 3
	;;
esac

:
