.TH ARMSTRAP-SUNXI-TOOLS "8" "April 2015" "Sunxi-Tools for allWinner's devices"
.SH NAME
armstrap-sunxi-tools \- Tools to help hacking Allwinner (aka sunxi) based devices.
.SH SYNOPSIS
.B fexc
[\fI-vq\fR] [\fI-I <fex|bin>\fR] [\fI-O <bin|fex>\fR] [\fI<input> \fR[\fI<output>\fR]]
.PP
(de)compiler for `.fex` configuration file.
.PP
.B fex2bin 
[\fI-vq\fR] [\fI<input> \fR[\fI<output>\fR]]
.PP
Compatibility shortcut to call `fexc` to decompile a binary blob back into `.fex` format.
.PP
.B bin2fex
[\fI-vq\fR] [\fI<input> \fR[\fI<output>\fR]]
.PP
Compatiblity shortcut to call `fexc` to compile a `.fex` file to binary blob.
.PP
.B nand-part
[\fI-f\fR \fIa10\fR|\fIa20\fR] \fInand-device\fR
.br
.B nand-part
\fInand-device\fR '\fIname2\fR \fIlen2\fR [\fIusertype2\fR]' ['\fIname3\fR l\fIen3\fR [\fIusertype3\fR]'] ...
.br
.B nand-part 
[\fI-f\fR \fIa10\fR|\fIa20\fR] \fInand-device\fR \fIstart1\fR '\fIname1\fR \fIlen1\fR [\fIusertype1\fR]' ['\fIname2\fR \fIlen2\fR [\fIusertype2\fR]'] ...
.br
.PP
Tool for manipulating Allwinner's NAND partition tables.
.PP
.SH DESCRIPTION
See the help of each tool for more information about its usage (\FI-?\FR).
.SH AUTHOR
Written by Alejandro Mery <amery@geeks.cl>
.SH "REPORTING BUGS"
Report bugs relative to tools at https://github.com/linux-sunxi/sunxi-tools/
.TP
Report bugs relative to armStrap at https://github.com/EddyBeaupre/armStrap/
.SH COPYRIGHT
Copyright \(co 2012 Alejandro Mery
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
