.TH armstrap-u-boot 8 "April 4, 2015" "" "armstrap-u-boot"

.SH NAME
armstrap-u-boot \- armStrap U-Boot bootloader manager.

.SH DESCRIPTION
This package is used for installing or updating the bootloader of all the devices supported by 
\fBarmStrap\fP.
.PP

.SH FILES
.TP
.BR /usr/share/armstrap-u-boot/<devices>/  \fR
Avalable bootloaders.
.TP
.BR /etc/armstrap.conf \fR
armStrap configuration.

.SH "SEE ALSO"
.TP
.BR armstrap-u-boot-installer \fR
 Installer script for the bootloaders.
